#ifndef AI4DOS_VERSION_H
#define AI4DOS_VERSION_H
#define AI4DOS_VERSION "0.1.0-beta.1"
#define AI4DOS_BETA 1
#if AI4DOS_BETA
#define AI4DOS_HEADER "AI4DOS " AI4DOS_VERSION
#define AI4DOS_VERSION_SUFFIX ""
#else
#define AI4DOS_HEADER "AI4DOS " AI4DOS_VERSION
#define AI4DOS_VERSION_SUFFIX ""
#endif
#endif
